DEFAULT:

  DeviceDataPath: 'Devices/Edge_Device/data'
  # DeviceDataPath: "D:/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data"
  AnalyticsOutBase: 'Devices/Analytics/'
  # AnalyticsOutBase: "D:/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Analytics/"
  IntervalDataGenerator: 1
  NumberOfSamplesGenerated: 50
  MessageBrokerHost: "localhost"
  QueueBase: "Queue"
  InputDimension: 9
  OutputDimension: 6
  NumberOfParticipants: 6
  Epochs: 1
  LearningRate: 1000
  Precision: 10000
  WaitingTime: 2
  BatchSize: 10
  Rounds: 300
  TestFilePath: 'Devices/Edge_Device/data/test_file.txt'
  # TestFilePath: "D:/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data/test_file.txt"
  TrainFilePath: 'Devices/Edge_Device/data/'
  # TrainFilePath: "D:/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Devices/Edge_Device/data/"
  IntervalTime: 40
  PercentOfDataGenerated: 0.0086
  #PerformProof: False
  PerformProof: true
  Gas: 100000000000000

  ResponseVariable: "Activity"
  EtheriumRPCServer: "http://127.0.0.1:8545"
  #change this when you compile the smart contract
  FLContractAddress: "0xc491F6A4Fd89ba5C4794E05768c26924d17d4b85"
  #change this when you compile the smart contract
  VerifierContractAddress: "0xeCBf0533B2535dE94bAeE28A953756957cdE8b38"
  VerifierAggregatorContractAddress: "0x7f56107D520fFa9C52e31751bee6f13F9a87F6a4"
  ZokratesPath: 'Verification/ZoKrates/root.zok'
  # ZokratesPath: "D:/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/ZoKrates/root.zok"
  VerificationBase: 'Verification/'
  # VerificationBase: "D:/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/SAVED_VERIFYER_10/"
  ZokratesBase: 'Verification/ZoKrates/'
  # ZokratesBase: "D:/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Verification/ZoKrates/"
  FLContractABIPAth: 'Blockchain/Truffle/build/contracts/FederatedModel.json'
  # FLContractABIPAth: "D:/Advancing-Blockchain-Based-Federated-Learning-Through-Verifiable-Off-Chain-Computations/Blockchain/Truffle/build/contracts/FederatedModel.json"
  Activities: [5, 11, 12, 14, 15, 17]
  ActivitiesEncoded: [1, 2, 3, 4, 5, 6]
  ActivityMappings:
    2: 1
    3: 1
    4: 1
    16: 15
    6: 5
    10: 11
    13: 14
    7: 1
  ActivityEncoding:
    5: 1
    11: 2
    12: 3
    14: 4
    15: 5
    17: 6
  # AnalyticsOutBase: 'Devices/MiddleWare/Analytics/'
  #  NumberOfParticipants: 6