DEFAULT:
  Activities:
  - 5
  - 11
  - 12
  - 14
  - 15
  - 17
  ActivitiesEncoded:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  ActivityEncoding:
    5: 1
    11: 2
    12: 3
    14: 4
    15: 5
    17: 6
  ActivityMappings:
    2: 1
    3: 1
    4: 1
    6: 5
    7: 1
    10: 11
    13: 14
    16: 15
  AnalyticsOutBase: 'devices/middleware/analytics/'
  BatchSize: 10
  DeviceDataPath: 'devices/edge_device/data'
  Epochs: 1
  EtheriumRPCServer: http://127.0.0.1:8545
  FLContractABIPAth: 'blockchain/Truffle/build/contracts/FederatedModel.json'
  FLContractAddress: '0xE255c86179D1bd746b637902F99239d0694AAFfa'
  Gas: 100000000000000
  InputDimension: 9
  IntervalDataGenerator: 1
  IntervalTime: 40
  LearningRate: 1000
  MessageBrokerHost: localhost
  NumberOfParticipants: 6
  NumberOfSamplesGenerated: 50
  OutputDimension: 6
  PercentOfDataGenerated: 0.0086
  PerformProof: true
  Precision: 10000
  QueueBase: Queue
  ResponseVariable: Activity
  Rounds: 5
  TestFilePath: 'devices/edge_device/data/test_file.txt'
  TrainFilePath: 'devices/edge_device/data/'
  VerificationBase: 'verification/'
  ZokratesBase: 'verification/zokrates/'
  VerifierContractAddress: '0xA16cdBA813F8F4c99181fBda46C7352a2991d881'
  VerifierAggregatorContractAddress: '0x566CE0F3f536bE0D019a39a1b9FB21Da76250A96'
  WaitingTime: 2
  ZokratesPath: 'verification/zokrates/root.zok'