#!/bin/bash

rm "./abi.json"
rm "./proof.json"
rm "./proving.key"
rm "./verification.key"
rm "./verifier.sol"
rm "./witness"
rm "./root"
rm "./root.r1cs"
rm "./out.r1cs"

rm "./ZoKrates/nested/abi.json"
rm "./ZoKrates/nested/proof.json"
rm "./ZoKrates/nested/proving.key"
rm "./ZoKrates/nested/verification.key"
rm "./ZoKrates/nested/verifier.sol"
rm "./ZoKrates/nested/witness"
rm "./ZoKrates/nested/out"
rm "./ZoKrates/nested/out.r1cs"