#!/bin/bash

rm "./abi.json"
rm "./proof.json"
rm "./proving.key"
rm "./verification.key"
rm "./verifier.sol"
rm "./witness"
rm "./root"
rm "./root.r1cs"
rm "./out.r1cs"
rm "./out"

rm "./ZoKrates/aggregator/abi.json"
rm "./ZoKrates/aggregator/proof.json"
rm "./ZoKrates/aggregator/proving.key"
rm "./ZoKrates/aggregator/verification.key"
rm "./ZoKrates/aggregator/verifier.sol"
rm "./ZoKrates/aggregator/witness"
rm "./ZoKrates/aggregator/out"
rm "./ZoKrates/aggregator/out.r1cs"